# Site settings
markdown: redcarpet
highlight: pygments
title: nginn-messagebus
email: rafal.gwizdala@gmail.com
tagline: lightweight .Net message bus
description: > # this means to ignore newlines until "baseurl:"
 is a lightweight .Net message bus / ESB framework that provides reliable and performant messaging infrastructure for your applications and services.
baseurl: "/nginn-messagebus-pages/" # the subpath of your site, e.g. /blog/
paginate: 5
# Build settings
markdown: kramdown

