# Site settings
title: nginn-messagebus
email: rafal.gwizdala@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  nginn-messagebus is a lightweight .Net message bus / ESB framework that provides reliable and performant messaging infrastructure for your applications and services. It uses a relational database as queue storage and builds on top of strong transactional/reliability guarantees provided by the database while making sure queue operations are as fast as possible.
baseurl: "/nginn-messagebus-pages/" # the subpath of your site, e.g. /blog/
paginate: 5
# Build settings
markdown: kramdown

